// <auto-generated />
using System;
using ConsoleBusinessCentral.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleBusinessCentral.Migrations
{
    [DbContext(typeof(ConsoleDbContext))]
    partial class ConsoleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleBusinessCentral.Models.Customer", b =>
                {
                    b.Property<string>("No")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Allow_Multiple_Posting_Groups")
                        .HasColumnType("bit");

                    b.Property<string>("Application_Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Balance_Due_LCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Balance_LCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Base_Calendar_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Blocked")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Combine_Shipments")
                        .HasColumnType("bit");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country_Region_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Coupled_to_CRM")
                        .HasColumnType("bit");

                    b.Property<bool?>("Coupled_to_Dataverse")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Credit_Limit_LCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency_Filter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Disc_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Posting_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Price_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Filter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fin_Charge_Terms_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gen_Bus_Posting_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Global_Dimension_1_Filter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Global_Dimension_2_Filter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IC_Partner_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Last_Date_Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_Terms_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Payments_LCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Post_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Privacy_Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("Reminder_Terms_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reserve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibility_Center")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Sales_LCY")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Salesperson_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Search_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ship_to_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shipping_Advice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shipping_Agent_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAT_Bus_Posting_Group")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("No");

                    b.ToTable("Customer", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
